[mgr]
prepend_keymap = [
	{ on = "d", run = "shell 'trash-put \"$@\"'", desc = "Remove files and directories with trash-cli" },
  { on = "<C-r>", run = "plugin relative-motions", desc = "Trigger a new relative motion" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
]
